name: Scaffold
options:
  bundleIdPrefix: com.piofusco
  platform: [ iOS ]
  deploymentTarget:
    iOS: 16.0
targets:
  Scaffold:
    sources:
      - Scaffold/
    platform: iOS
    type: application
    info:
      path: Scaffold/Info.plist
    settings:
      base:
        SUPPORTS_MACCATALYST: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        TARGETED_DEVICE_FAMILY: 1
  ScaffoldTests:
    sources:
      - ScaffoldTests/
    dependencies:
      - target: Scaffold
    platform: iOS
    type: bundle.unit-test
    info:
      path: ScaffoldTests/Info.plist
    settings:
      base:
        SUPPORTS_MACCATALYST: false
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
        TARGETED_DEVICE_FAMILY: 1
schemes:
  Scaffold:
    build:
      targets:
        Scaffold: all
    archive:
      config: Release
      customArchiveName: Scaffold
      revealArchiveInOrganizer: false
  ScaffoldTests:
    build:
      targets:
        ScaffoldTests: [test, run]
    test:
      targets:
        - name: ScaffoldTests
          parallelizable: true
          randomExecutionOrder: true
          skippedTests: []