name: Continuous Integration
# Run CI on pull request opens, as well as synchronize (push) events
on: [pull_request, push]
jobs:
  build:
    runs-on: macOS-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Xcode Configuration
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.1.0'
      - name: Install Xcodegen
        run: brew install xcodegen
      - name: Generate project
        run: xcodegen generate
      - name: Run Unit Tests
        run: |
          xcodebuild -scheme ScaffoldTests -destination 'platform=iOS Simulator,name=iPhone SE (3rd generation),OS=16.1' -resultBundlePath TestResults clean test
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()
